-- 코드를 입력하세요
SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT from ONLINE_SALE
where YEAR(SALES_DATE) = 2022 and month(SALES_DATE) = 3
union all
SELECT SALES_DATE, PRODUCT_ID, NULL, SALES_AMOUNT from OFFLINE_SALE
where YEAR(SALES_DATE) = 2022 and month(SALES_DATE) = 3
order by SALES_DATE, PRODUCT_ID, USER_ID;