WITH RECURSIVE GEN AS (
    -- 1) 시작점 (앵커): 1세대
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    -- 2) 재귀: 이전 세대의 자식을 찾아 세대 +1
    SELECT E.ID, G.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN GEN G ON E.PARENT_ID = G.ID
)
SELECT count(*) AS COUNT, GENERATION FROM GEN
WHERE ID NOT IN (SELECT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION;