-- 코드를 입력하세요
SELECT F.TITLE, I.BOARD_ID, I.REPLY_ID, I.WRITER_ID, I.CONTENTS, I.CREATED_DATE from USED_GOODS_REPLY I 
join USED_GOODS_BOARD F on F.BOARD_ID = I.BOARD_ID
where YEAR(F.CREATED_DATE) = 2022 and MONTH(F.CREATED_DATE) = 10
order by I.CREATED_DATE asc, F.TITLE asc;